// <auto-generated />
using System;
using Lab3_wk4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab3_wk4.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Lab3_wk4.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            name = "Family"
                        },
                        new
                        {
                            CategoryId = 2,
                            name = "Friend"
                        },
                        new
                        {
                            CategoryId = 3,
                            name = "Work"
                        },
                        new
                        {
                            CategoryId = 4,
                            name = "Other"
                        });
                });

            modelBuilder.Entity("Lab3_wk4.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            CategoryId = 1,
                            DateAdded = new DateTime(2021, 2, 11, 0, 16, 15, 930, DateTimeKind.Local).AddTicks(8453),
                            Email = "bruce.wayne@domain.com",
                            FirstName = "Bruce",
                            LastName = "Wayne",
                            Phone = "416-123-4567"
                        },
                        new
                        {
                            ContactId = 2,
                            CategoryId = 2,
                            DateAdded = new DateTime(2021, 2, 11, 0, 16, 15, 931, DateTimeKind.Local).AddTicks(4779),
                            Email = "peter.parker@domain.com",
                            FirstName = "Peter",
                            LastName = "Parker",
                            Phone = "647-123-4567"
                        },
                        new
                        {
                            ContactId = 3,
                            CategoryId = 3,
                            DateAdded = new DateTime(2021, 2, 11, 0, 16, 15, 931, DateTimeKind.Local).AddTicks(4801),
                            Email = "diana.prince@domain.com",
                            FirstName = "Diana",
                            LastName = "Prince",
                            Phone = "905-123-4567"
                        });
                });

            modelBuilder.Entity("Lab3_wk4.Models.Contact", b =>
                {
                    b.HasOne("Lab3_wk4.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
